### ISSUE TITLE
.send(f'{new_message[0]}')

### ISSUE THREAD

**Issue by FunnyWay1985** [npcx42/TeleRelayBot#1]
Всё заполнил корректно, но при старте бота пишет выдаёт ошибку. 
![parsecd_EWz2bZ5ZpN](https://github.com/npcx42/telegram-to-discord-bot/assets/110125078/5fd9151e-4072-4f53-af99-124487da9848)

Единственное, что изменил, в bot.py:

        # * * * * * */20 - 20 seconds
        # 0 */1 * * * - 1 hour
        @aiocron.crontab('* * * * * */20')

**Comment by sinkclose** [comment]
попробуйте сменить имя папок на английский язык и не использовать пробелы в них.

**Comment by sinkclose** [comment]
так же советую переустановить сорс. я пофиксил туториал и указал что теперь нужно использовать config.ini

**Comment by FunnyWay1985** [comment]
К сожалению, таже ошибка.
![parsecd_YR0mbe7KZ9](https://github.com/npcx42/telegram-to-discord-bot/assets/110125078/4cef0e39-83a3-499d-8207-fdb772c74551)

Пробовал:
Перенести в корень и на рабочий стол
Переустановить python
Снова делать pip install -r requirements.txt
Переключаться между main и lastest

config.ini заполнен
![Rainmeter_6CMOjG68WB](https://github.com/npcx42/telegram-to-discord-bot/assets/110125078/8cd8f36b-01e3-4e95-8dbf-3266dc2c9038)

Кроме заполнения конфига, только здесь внёс изменение
![parsecd_Ym5y3ObLHY](https://github.com/npcx42/telegram-to-discord-bot/assets/110125078/6bb481ea-b377-4293-83cc-9b2cc7512d98)

**Comment by FunnyWay1985** [comment]
Всё, что есть в папке
![parsecd_xTMizv5NJG](https://github.com/npcx42/telegram-to-discord-bot/assets/110125078/aa8dd170-2586-4a2d-883e-d82712bc9d26)

**Comment by FunnyWay1985** [comment]
Полностью выглядит так
![parsecd_j6uR2uM56m](https://github.com/npcx42/telegram-to-discord-bot/assets/110125078/31b1e250-d951-41aa-889d-cd8ca0c30f08)

**Comment by FunnyWay1985** [comment]
Если здесь убрать [0], то сообщение приходит, но в таком виде:
![parsecd_5BMr1cYU3F](https://github.com/npcx42/telegram-to-discord-bot/assets/110125078/2ac6d319-de73-4981-a502-0eaf59b56771)
![Discord_3SPIdL0fqd](https://github.com/npcx42/telegram-to-discord-bot/assets/110125078/d41250ed-c170-4d52-ae70-8ac14c9221a9)

В ином случае, сообщения не приходят и отображается ошибка

**Comment by unsertod** [comment]
Это приколы Python, исправлю немного позже.

**Comment by unsertod** [comment]
Смотри, выполни те задачи которые здесь написаны:
- Замени `new_message[0]` на `message_data`, либо установи Python на версию 3.10.8 и попробуй, не должно такого происходить. Ни раз проверялось, всё работало:
![изображение](https://github.com/npcx42/telegram-to-discord-bot/assets/103527176/71ba4b66-f1d0-4318-821e-f776ab793297)
![изображение](https://github.com/npcx42/telegram-to-discord-bot/assets/103527176/4a6d71cf-acab-499b-9933-567fb39a71fc)
- Либо же у тебя постов нет, из-за чего происходит такое. (Ты замазал ссылку на канал, проверить сам не могу)

**Comment by ExtbhiteEAS** [comment]
Либо же у тебя постов нет, из-за чего происходит такое. Ты замазал ссылку на канал, проверить сам не могу.

**Comment by FunnyWay1985** [comment]
К сожалению, также. 
![parsecd_HzJGraSsJD](https://github.com/npcx42/telegram-to-discord-bot/assets/110125078/c304f3f2-a65f-4ef6-a04b-f8277b7b0c3f)

Смена версии не помогла, каналы, которые пробовал https://t.me/VALORANT_University и https://t.me/vladchertest

**Comment by unsertod** [comment]
Ссылка на канал должен быть таким: `https://t.me/s/vladchertest`, а не просто `https://t.me/vladchertest`.

**Comment by unsertod** [comment]
![изображение](https://github.com/npcx42/telegram-to-discord-bot/assets/103527176/631d399c-d481-4899-8efa-4db6caad2f83)
Советую немного внимательно просмотреть пример файла, ссылка на публичный канал должен начинаться с `https://t.me/s/`, так как скрипт парсит текст с web-сайта Телеграма.

**Comment by FunnyWay1985** [comment]
Да, теперь всё работает в том числе на python 11. Моя невнимательность, огромное спасибо за помощь!
